version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydatabase

  express:
    build: ./backend
    container_name: express-server
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - PORT=5000
    depends_on:
      - mongo
    command: ["npm", "start"]
volumes:
  mongo-data:
